[package]
name = "cargo-android"
version = "0.1.0"
authors = ["Bailey Cosier <bailey.cosier@gmail.com>"]
license = "MIT"
description = "Cargo subcommand providing Android build support and automation"
repository = "https://github.com/cosier/cargo-android"

[dependencies]
clap = "^2.25.1"
toml = "0.4.2"
term = "0.4.6"

serde = "^1.0.10"
serde_derive = "^1.0.10"
serde_json = "^1.0.2"
